apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: tf-scheduler
spec:
  description: TODO
  params:
    - name: PULL_SECRET_NAME
    - name: TESTING_FARM_TOKEN_SECRET_NAME
  volumes:
    - name: pull-secret-volume
      secret:
        secretName: "$(params.PULL_SECRET_NAME)"
    - name: testing-farm-secret
      secret:
        secretName: "$(params.TESTING_FARM_TOKEN_SECRET_NAME)"
  results:
    - name: tf-request
  steps:
    - name: future-pre-process
      image: quay.io/testing-farm/cli:latest
      volumeMounts:
        - name: pull-secret-volume
          mountPath: "/etc/secrets/pull-secret-volume"
          readOnly: true
        - name: testing-farm-secret
          mountPath: "/etc/secrets/testing-farm-secret"
          readOnly: true            
      script: |
            #!/usr/bin/env bash
            export TESTING_FARM_API_TOKEN=$(cat /etc/secrets/testing-farm-secret/testing-farm-token)

            echo -n "FOO" > $(results.tf-request.path)
