apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: testing-farm
spec:
  description: TODO
  params:
    - name: SNAPSHOT
      description: A list of container images that should undergo testing
    - name: APPLICATION
    - name: COMPONENT
  steps:
    - image: quay.io/testing-farm/cli:latest
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: APPLICATION
          value: $(params.APPLICATION)
        - name: COMPONENT
          value: $(params.COMPONENT)          
      script: |
            #!/usr/bin/env bash
            env | sort            
            
