apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: testing-farm
spec:
  description: TODO
  params:
    - name: SNAPSHOT
      description: A list of container images that should undergo testing
  steps:
    - image: quay.io/testing-farm/cli:latest
      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: APPLICATION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/application']
        - name: COMPONENT
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['appstudio.openshift.io/component']          
      script: |
            #!/usr/bin/env bash
            env | sort            
            
