apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tmt-via-testing-farm
spec:
  description: >-
    TODO
  params:
    - name: SNAPSHOT
      description: A list of container images that should undergo testing
  tasks:
    - name: testing-farm
      timeout: "5h"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/lukaszachy/testing-farm-tekton
          - name: revision
            value: one-app-more-comps
          - name: pathInRepo
            value: tasks/testing-farm.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
