apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tmt-via-testing-farm
spec:
  description: >-
    TODO
  params:
    - name: SNAPSHOT
      description: A list of container images that should undergo testing
    - name: PULL_SECRET_NAME
      description: Explicit name of pull secret to use, detected by app/comp name otherwise
      default: ""
    - name: TESTING_FARM_TOKEN_SECRET_NAME
      default: "testing-farm-secret"
      description: Name of the Key/Value secret with testing-farm-token key
    - name: GIT_URL
      default: ""
      description: URL of the GIT repository that contains the tests.
    - name: TMT_PLAN
      default: "."
      description: Name filter for plans defined in the repo.
    - name: GIT_REF
      default: ""
      description: Branch of the git repository used containing the tests
    - name: COMPOSE
      default: "Fedora-40"
      description: Compose to use for the system-under-test.
    - name: ARCH
      default: "x86_64"
      description: Comma-separated list of architectures to run against.
    - name: TIMEOUT
      default: "720"
      description: Set the timeout for the request in minutes. If the test takes longer than this, it will be terminated.
    - name: TESTING_FARM_API_URL
      default: https://api.dev.testing-farm.io/v0.1
      description: The testing-farm instance API to use
  results:
    - name: REQUEST_URL
      value: "$(tasks.schedule.results.tf-request)"
  tasks:
    - name: pre-process
      timeout: "5m"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/lukaszachy/testing-farm-tekton
          - name: revision
            value: one-app-more-comps
          - name: pathInRepo
            value: tasks/pre-process.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
    - name: schedule
      runAfter:
        - pre-process
      timeout: "5m"
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/lukaszachy/testing-farm-tekton
          - name: revision
            value: one-app-more-comps
          - name: pathInRepo
            value: tasks/scheduler.yaml
      params:
        - name: PULL_SECRET_NAME
          value: "$(tasks.pre-process.results.pull-secret-name)"
        - name: TESTING_FARM_TOKEN_SECRET_NAME
          value: "$(params.TESTING_FARM_TOKEN_SECRET_NAME)"
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)          